title: Oliver Lundquist
email: mail@oliverlundquist.com
description: "I blog about tech, travel and freelancing."
baseurl: ""
url: "https://oliverlundquist.com"
twitter_username: lundquistoliver
github_username:  oliverlundquist
google_analytics: UA-106187968-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
